CC = gcc
LD = gcc
CFLAGS = -I. -O0
OBJS = header.o tablehotfix.o regularhotfix.o meshhotfix.o
LIBRARIES = libbl3mod.a
PROGS_OBJS = dialog.o
PROGS = dialog
PREFIX = /usr/local

all: $(LIBRARIES) $(PROGS)

.SUFFIXES: .c .h .o

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

$(LIBRARIES): $(CPROTOS) $(OBJS)
	ar cr libbl3mod.a $(OBJS)

$(PROGS): $(PROGS_OBJS) $(LIBRARIES)
	$(CC) -o dialog dialog.o -L. -lbl3mod

.PHONY: clean

clean:
	rm -f $(OBJS) $(PROGS_OBJS) $(LIBRARIES) $(PROGS)
