CC = cl
LD = link
CFLAGS = /c
OBJS = header.obj tablehotfix.obj regularhotfix.obj meshhotfix.obj utilunique.obj utilgame.obj
LIBRARIES = libbl3mod.lib
PREFIX = /usr/local

all: $(LIBRARIES)

.SUFFIXES: .c .h .obj

.c.obj:
	$(CC) $(CFLAGS) $<

$(LIBRARIES): $(CPROTOS) $(OBJS)
	lib /out:libbl3mod.lib $(OBJS)

.PHONY: clean

clean:
	del $(OBJS) $(LIBRARIES)
