CC = gcc
LD = gcc
CFLAGS = -I. -O0
OBJS = header.o tablehotfix.o regularhotfix.o meshhotfix.o utilunique.o utilgame.o
LIBRARIES = libbl3mod.a
PREFIX = /usr/local

all: $(LIBRARIES)

.SUFFIXES: .c .h .o

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

$(LIBRARIES): $(OBJS)
	ar cr libbl3mod.a $(OBJS)

progs:
	make -C EXAMPLES -f Makefile.bsd

.PHONY: clean

clean:
	rm -f $(OBJS) $(LIBRARIES)
	make -C EXAMPELS -f Makefile.bsd
