$! ON ERROR $ CONTINUE
$ CC HEADER.C
$ CC REGULARHOTFIX.C
$ CC TABLEHOTFIX.C
$ CC MESHHOTFIX.C
$ LIBRARY/CREATE LIBBL3MOD HEADER.OBJ,REGULARHOTFIX.OBJ,TABLEHOTFIX.OBJ
$ CC DIALOG.c
$ LINK DIALOG,LIBBL3MOD.OLB/LIB