SYSTEM = os2v2
CC = wcc386
LD = wlib
CFLAGS = -bt=$(SYSTEM) -bc
OBJS = header.obj tablehotfix.obj regularhotfix.obj meshhotfix.obj
PROGS_OBJS = dialog.obj
PROGS = dialog.exe
LIBRARIES = libbl3mod.lib

all: $(LIBRARIES) $(PROGS)

.c.obj:
	$(CC) $(CFLAGS) $<

$(LIBRARIES): $(OBJS)
	wlib libbl3mod.lib +header.obj +tablehotfix.obj +regularhotfix.obj +meshhotfix.obj

$(PROGS): $(PROGS_OBJS)
	wlink system $(SYSTEM) file dialog.obj file libbl3mod.lib

clean:
	rm -f $(OBJS) $(LIBRARIES) $(PROGS)
