CC = cl
LD = link
CFLAGS = /c
OBJS = header.obj tablehotfix.obj regularhotfix.obj meshhotfix.obj
PROGS_OBJS = dialog.obj
PROGS = dialog.exe
LIBRARIES = libbl3mod.lib
PREFIX = /usr/local

all: $(LIBRARIES) $(PROGS)

.SUFFIXES: .c .h .obj

.c.obj:
	$(CC) $(CFLAGS) $<

$(LIBRARIES): $(CPROTOS) $(OBJS)
	lib /out:libbl3mod.lib $(OBJS)

$(PROGS): $(PROGS_OBJS) $(LIBRARIES)
	$(LD) /out:dialog.exe dialog.obj libbl3mod.lib

.PHONY: clean

clean:
	del $(PROGS) $(LIBRARIES) $(OBJS) $(PROGS_OBJS)
