SYSTEM = nt
CC = wcc386
LD = wlib
CFLAGS = -bt=$(SYSTEM) -bc
OBJS = header.obj tablehotfix.obj regularhotfix.obj meshhotfix.obj utilunique.obj utilgame.obj
PROGS_OBJS = dialog.obj
PROGS = dialog.exe
LIBRARIES = libbl3mod.lib

all: $(LIBRARIES)

.c.obj:
	$(CC) $(CFLAGS) $<

$(LIBRARIES): $(OBJS)
	wlib libbl3mod.lib +header.obj +tablehotfix.obj +regularhotfix.obj +meshhotfix.obj +utilgame.obj +utilunique.obj

clean:
	del $(OBJS) $(LIBRARIES)
